name = "Uniformization"
uuid = "f44d862a-bb5d-4651-8b42-7616042c4b61"
authors = ["Garrett Smith <gasmith@uni-potsdam.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
